FROM python:slim

RUN apt -y update && apt -y install git

COPY requirements.txt /root/
RUN pip install -U pip \
    && pip install -r /root/requirements.txt

CMD [ "bash", "/mnt/start-local.sh" ]

WORKDIR /mnt
